# Generated by Django 5.0.7 on 2024-11-08 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0002_remove_match_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='start_date',
        ),
    ]
