# Generated by Django 5.0.7 on 2024-11-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0003_remove_tournament_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
