# Generated by Django 5.0.7 on 2024-11-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0004_participant_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='nickname',
            field=models.CharField(default='Default Nickname', max_length=50),
            preserve_default=False,
        ),
    ]
