# Generated by Django 5.0.7 on 2024-11-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0008_tournament_max_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='participant1_score',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='participant2_score',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='nickname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='max_participants',
            field=models.PositiveIntegerField(default=16),
        ),
    ]
