# Generated by Django 5.0.7 on 2024-10-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(max_length=30, verbose_name='TYPE')),
                ('room_id', models.IntegerField(blank=True, null=True, verbose_name='ROOM_ID')),
                ('state', models.CharField(default='load', max_length=30, verbose_name='STATE')),
            ],
        ),
    ]
